package Utils;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.pagefactory.AjaxElementLocatorFactory;
import org.openqa.selenium.support.pagefactory.ElementLocatorFactory;
import org.stringtemplate.v4.ST;

public class Locators extends BasePage {
    int DRIVER_WAIT = 5;

    public Locators(WebDriver driver) {
        ElementLocatorFactory finder = new AjaxElementLocatorFactory(driver, DRIVER_WAIT);
        PageFactory.initElements(finder, this);
        this.driver = driver;
    }

    @FindBy(xpath = "//p[@class='xsmall strong ng-star-inserted']//..//..//..//input")
    protected WebElement inputViewName;
    @FindBy(xpath = "//span[contains(text(),'Continue')]")
    protected WebElement continueButton;
    @FindBy(xpath = "//input[@id='loginEmail']")
    protected WebElement username;
    @FindBy(xpath = "//input[@id='loginPassword']")
    protected WebElement password;
    @FindBy(xpath = "//div[@class='col-12 d-flex justify-content-center mb-4']")
    protected WebElement loginButton;
    @FindBy(xpath = "//div[@class='swiper-slide swiper-slide-active']//div[@class='absolute left-0 top-0 h-full w-full']//div[@class='relative h-full w-full']")
    protected WebElement videoFeed;
    @FindBy(xpath = "//tbody/tr[1]")
    protected WebElement showUploadVideoInDataLog;
//    @FindBy(xpath = "//label[contains(normalize-space(),'300')][@for='mission']")
//    protected WebElement CHARLIMIT_FOR_MISSION;

    // Locator For
    public static String usernameLogin = "//input[@id='loginEmail']";
    public static String passLogin = "//input[@id='loginPassword']";
    public static String loginBtn = "//div[@class='col-12 d-flex justify-content-center mb-4']";
    public static String SELECT_ANY_BRAND = "//h6[normalize-space()='TCS']";
    public static String DASHBOARD_SCREEN = "//span[normalize-space()='Build']";
    public static String ADD_BRAND_ELEMENT = "//div[@class='d-flex align-items-center'][.='Add Brand Elements']";
    public static String BRAND_PERSONA = "//button[contains(@class,'btn w-100 text-start rounded-1 mt-2 d-flex')][text()='Brand Persona']";
    public static String MISSION_BRANDPERSONA = "//label[@for='mission'][1]";
    public static String VISION_BRANDPERSONA = "(//label[@for='vision'])[1]";
    public static String VALUE_BRANDPERSONA = "(//label[@for='values'])[1]";
    public static String POLICIES_BRANDPERSONA = "//body/div[@id='__next']/div[@class='app']/div[@class='wrapper']/main[@class='content']/div[@class='page-wrapper container-fluid']/div[@class='page onboard position-relative container-fluid']/div[@class='row h-100']/div[@class='col-12 col-md-9 pb-4']/div[@class='card card-stretch-full mb-0']/div[@class='card-body card-body-scrollable persona-details']/div[4]/div[1]/div[1]/span[1]";
    public static String PROCEDURES_BRANDPERSONA = "//span//label[@for='procedures']";
    public static String WORKING_CONDITIONS_BRANDPERSONA = "//span//label[@for='working_conditions']";
    public static String CODE_OF_CONDUCT_BRANDPERSONA = "//span//label[@for='code_of_conduct']";
    public static String DO_AS_BRANDPERSONA = "//span//label[@for='dos']";
    public static String DONT_AS_BRANDPERSONA = "//span//label[@for='donts']";
    public static String DOCUMENT_BRANDPERSONA = "//h5[normalize-space()='Upload docs']";
    public static String CHARLIMIT_FOR_MISSION = "//label[contains(normalize-space(),'300')][@for='mission']";
    public static String CHARLIMIT_FOR_VISION = "//label[contains(normalize-space(),'300')][@for='vision']";
    public static String CHARLIMIT_FOR_POLICIES = "//label[contains(normalize-space(),'1000')][@for='policies']";
    public static String CHARLIMIT_FOR_WORKING_CONDITIONS = "//label[contains(normalize-space(),'500')][@for='working_conditions']";
    public static String CHARLIMIT_FOR_CODE_OF_CONDUCT = "//label[contains(normalize-space(),'1000')][@for='code_of_conduct']";
    public static String CHARLIMIT_FOR_DO_AS = "//label[contains(normalize-space(),'1000')][@for='dos']";
    public static String CHARLIMIT_FOR_DONT_AS = "//label[contains(normalize-space(),'1000')][@for='donts']";
    public static String MISSION_FIELD = "//textarea[@id='mission']";
    public static String VISION_FIELD = "//textarea[@id='vision']";
    public static String VALUES_FIELD = "(//a[@class='react-tagsinput-remove'])";
    public static String POLICIES_FIELD = "//textarea[@id='policies']";
    public static String PROCEDURE_FIELD = "//textarea[@id='procedures']";
    public static String WORKING_CONDITIONS_FIELD = "//textarea[@id='working_conditions']";
    public static String CODE_OF_CONDUCT_FIELD = "//textarea[@id='code_of_conduct']";
    public static String DO_AS_FIELDS = "(//div[contains(@class,'react-tagsinput')])[4]";
    public static String DONT_AS_FIELD = "(//div[contains(@class,'react-tagsinput')])[6]";
    public static String DOCUMENT_FIELD = "//div[@class='d-flex align-items-center justify-content-between p-3 rounded-1 mt-2']";
    public static String REMOVE_BUTTON_BRANDPERSONA_DOCUMENT_FIELD = "//button[normalize-space()='Remove']";
    public static String CONTINUE_BUTTON_DISABLE_BRANDPERSONA = "//button[@class='btn btn-info disabled']";
    public static String LAUNCH_COMMUNITY_MEDIA_NETWORK = "//div[normalize-space()='Launch Community Media Network']";
    public static String BRAND_TYPE = "//button[normalize-space()='Brand type']";
    public static String RETAIL_NETWORK_OR_MARKET_PLACE = "//label[normalize-space()='Retail Network/ Marketplace']";
    public static String SELECT_BRAND_TRAFFIC_UNDER_1M = "//input[@id='trafficOne']";
    public static String CONSUMER_BRANDS = "//button[contains(.,'Consumer Brands')]";
    public static String TERMS_SHEET = "//button[normalize-space()='Term Sheet']";
    public static String NETWORK_OR_MARKET_PLACE_CONTINUE_BUTTON = "//button[normalize-space()='Continue']";
    public static String PUBLISH_YOUR_COMMUNITY_TEXT = "//div[contains(@class,'wrapper')]//div[3]//button[1]//div[1]";
    public static String OPTIONS_TRAFFIC_RANGE = "//div[@class='d-flex gap-3']/child::div";
    public static String BRAND_TYPE_MEDIA = "//div[@aria-labelledby='categoryTwoLabel']";
    public static String ALERT_MESSAGE = "//div[@role='alert']";
    public static String BRAND_TYPE_CONSUMER = "//label[normalize-space()='Consumer']";
    public static String CONSUMER_BRANDS_DISABLED = "(//div[contains(@class,'collapse show')])[2]";
    public static String TERM_SHEET_DISABLED = "(//div[contains(@class,'collapse show')])[3]";
    public static String SELECT_BRAND_TRAFFIC_1M_5M = "//label[normalize-space()='1M - 5M']";
    public static String SELECT_BRAND_TRAFFIC_5M_10M = "//label[normalize-space()='5M - 10M']";
    public static String SELECT_BRAND_TRAFFIC_MORE_THAN_10M = "//label[normalize-space()='More than 10M']";
    public static String NEXT_SECTION_CONSUMER_BRANDS = "//button[contains(.,'Consumer Brands')]";
    public static String TEXT_AREA_OF_MISSION = "//textarea[@id='mission']";

    //Add Consumer Brand
    public static String TITLE_CONSUMER_BRAND = "//h4[normalize-space()='Add consumer brands to your network']";
    public static String ADD_CONSUMER_BRAND_BUTTON = "//button[normalize-space()='Add Brand to Earn']";
    public static String BRAND_USERNAME_CONSUMER_BRAND = "//input[@id='genuin_id']";
    public static String PUMA_SPORT_BRAND = "//div[@class='d-flex gap-2']//div";
    public static String CPM_FLOOR_PRICE = "//input[@id='cpm']";
    public static String YOUTUBE_HANDLE = "//input[@id='handles[6].inputValue']";
    public static String ADD_BUTTON = "//button[normalize-space()='Add']";
    public static String ADD_SOCIAL_HANDLE = "//button[normalize-space()='+ Add Social Handle']";

    //Term Sheet
    public static String PRIMARY_CONTACT_TERM_SHEET = "//legend[@class='h6 form-label mb-3 text-gray-800 fw-semibold']";
    public static String FULL_NAME = "//input[@name='msa.0.signerName']";
    public static String CONTACT_EMAIL = "//input[@name='msa.0.signerEmail']";
    public static String LEGAL_TEAM_ADD_PERSON_BUTTON = "//legend[contains(text(),'Legal Team for Review')]/descendant::button";
    public static String LEGAL_TEAM_FOR_REVIEW = "//legend[contains(text(),'Legal Team for Review')]";
    public static String PERSON_1_NAME_FOR_LEGAL_TEAM_REVIEW = "//input[@id='msa.0.legalTeamCC.0.name']";
    public static String PERSON_1_EMAIL_FOR_LEGAL_TEAM_REVIEW = "//input[@id='msa.0.legalTeamCC.0.email']";
    public static String TEAM_MEMBERS_FOR_NOTICE = "//legend[contains(.,'Team Members for Notice')]";
    public static String ADD_A_PERSON_BUTTON_TEAM_MEMBER = "//legend[contains(.,'Team Members for Notice')]/descendant::button";
    public static String PERSON_1_NAME_FOR_NOTICE_TEAM = "//input[@id='msa.0.legalNotificationCC.0.name']";
    public static String PERSON_1_EMAIL_FOR_NOTICE_TEAM = "//input[@id='msa.0.legalNotificationCC.0.email']";
    public static String SKIP_BUTTON = "//button[normalize-space()='Skip for now']";
    public static String CONTINUE_TERM_SHEET = "//button[normalize-space()='Skip for now']";
    public static String VALIDATION_TOASTER = "//div[@class='rnc__notification-title']";
    public static String LEGAL_TEAM_ADD_PERSON_BUTTON_CLICKBLE = "//button[normalize-space()='+ Add person']";
    public static String PERSON_2_LEGAL_TEAM = "//h6[normalize-space()='Person 2:']";
    public static String NOTICE_TEAM_ADD_PERSON_BUTTON_CLICKBLE = "//button[normalize-space()='+ Add a person']";
    public static String PERSON_2_NOTICE_TEAM = "//h6[normalize-space()='Person 2:']";
    public static String VALIDATIONMESSAGEFORCONTACTNAME = "//div[normalize-space()='Enter your name']";
    public static String VALIDATIONMESSAGEFORCONTACTEMAIL = "//div[normalize-space()='Enter your Email']";

    //FE Home page
    public static String POPULAR_OPTION = "//p[normalize-space()='Popular']";
    public static String HEADER_FRONTEND = "//nav[@class='sticky top-0 flex h-full w-full items-center justify-between gap-6 px-2 2xl:container xl:px-10 2xl:px-0']";
    public static String DOWNLOAD_OPTION = "//p[@class='text-new-para-2 font-semibold text-tertiary-100']";
    public static String POPUP_VISIABLE = "//div[@id='radix-:rh:']";
    public static String HOME_OPTION = "//p[@class='hidden whitespace-nowrap !text-title-2-demi xl:block text-primary']";
    public static String VIDEO_FEED = "//div[@class='swiper-slide swiper-slide-active']//div[@class='absolute inset-0']";
    public static String Log_In = "//button[@class='inline-flex items-center justify-center rounded-md transition-colors focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary-600 after::bg-primary-600 py-2 h-8 gap-2 px-4']";
    public static String EMAIL_FIELD = "//input[@name='email']";
    public static String CONTINUE_BUTTON = "//button[@type='submit']";
    public static String ENTER_OTP = "//input[@name='otp']";
    public static String VERIFY_BUTTON = "//p[@class='text-title-3-demi']";
    public static String CheckboxBrandGuidelines = "//button[@role='checkbox' and @type='button']";
    public static String ClickFirstInterest = "//p[normalize-space()='Audience Segmentation in Healthcare']";
    public static String ClickSecondInterest = "//p[normalize-space()='Taxation on Crypto Currency']";
    public static String ClickThirdInterest = "//p[normalize-space()='Mandatory HSN For GST E Invoice']";

    //ENGAGE Engine
    public static String VIEW = "//button[normalize-space(text())='View']";
    public static String importVideoButton = "//span[contains(text(),'Import Videos')]";
    public static String engageEngineButton = "//span[normalize-space()='Engage']";
    public static String uploadFolderButton = "//span[normalize-space()='Uploads']";
    public static String fileInputPath = "//input[@type='file']";
    //public static String importButton = "//button[normalize-space()='Import']";
    public static String verifyMessage = "//div[@class='rnc__notification-message']";
    public static String socialImportButton = "//span[normalize-space()='Social Import']";
    public static String checkbox = "//input[@id='checkbox-select-all']";
    public static String dataLogButton = "//span[contains(text(),'Data Logs')]";
    public static String activityButton = "//span[contains(text(),'Activity')]";
    public static String pendingButton = "//button[normalize-space()='Pending']";
    public static String videoLink = "//img[contains(@src, 'scrapped_assets/youtube/thumbnails')]/@src";
    public static String exapandArrow = "//div[@class='bg-gray-100 border-radius-8']";
    public static String MangeHandles = "//a[@href='/settings/profile'][normalize-space()='Manage handles']";
    public static String addSocialHandle = "//button[normalize-space()='+ Add Social Handle']";
    public static String youtuubeHandle = "(//*[@class=\"form-control\"])[last()]";
    public static String saveButton = "//button[normalize-space()='Save']";
    public static String helloVisible = "//label[normalize-space()='@hello']";
    public static String NextButton = "(//button[contains(@type,'button')])[12]";
    public static String NEXTBUTTON = "//button[@class='btn btn-light-light btn-only-icon bg-gray-100']";
    public static String deleteButton = "(//button[@aria-label='Delete'])[last()]";
    public static String BRANDCATEGOIES = "//button[@class='btn w-100 text-start rounded-1 mt-2 d-flex btn-light-info active-tab']";
    public static String SEARCHFIELDLOGIN = "//input[@type='search' or @placeholder='search']";
    public static String EMAILFIELD = "//input[@id='email']";
    public static String PASSWORDFIELD = "//input[@id='loginPassword']";
    public static String HOMELOGO = "//div[@class='aside-head']";
    public static String SEARCHFIELDONHOME = "//input[@placeholder='Search']";
    public static String SEARCHVALUEHOME = "//div[@role='button']//span[@class='text-truncate']";
    public static String GROWMENU = "//span[contains(text(),'Grow')]";
    public static String NEWBTN = "//button[contains(text(),'New')]";
    public static String EMBEDSTYLEDRP = "//select[@id='embed-style']";
    public static String HEADLINEFIELD = "//input[@id='headline']";
    public static String MODERATEMENU = "//span[contains(text(),'Moderate')]";
    public static String HISTORTBTN = "//button[contains(.,'History')]";
    public static String FILTERBTN = "//button[contains(text(),'Filter')]";
    public static String DELETEDCHECKBOX = "//label[@for='action_deleted']";
    public static String PAGENATIONDRP = "//select[@class='form-select form-select-sm']";
    public static String DELETECOUNTALL = "//td//span[contains(text(),'Deleted')]";
    public static String ENGAGEMENU = "//a[contains(.,'Engage')]";
    public static String IMPORTVIDEO = "//a[contains(.,'Import Videos')]";
    public static String UPLOADVIDEO = "//p[contains(text(),'Bulk upload short form videos')]";
    public static String UPLOAD = "//button[normalize-space()='Choose files']";
    public static String CHOOSEFILE = "//button[.='Choose files']";
    public static String IMPORTBTN = "//button[@class='btn btn-info']";
    public static String YOURCOMPUTER = "//*[contains(.,'Your Computer')]";
    public static String SIGNUPLINK = "//a[.='Sign up']";
    public static String ENTEREMAILADDRESS = "//div[@class='col-12 mt-5 position-relative']//span";
    public static String EMAILFIEDL = "//input[@id='email'] | //input[@autocomplete='email']";
    public static String SETYOURPASSWORDFIELD = "//input[@id='password']";
    public static String AGREEANDCONTINUE = "//div[contains(text(),'Agree and Continue')]";
    public static String CONTINUEWITHGOOGLE = "//span[contains(.,'Continue with Google')]";
    public static String FORGOTPASSWORD = "//a[contains(.,'Forgot password')]";
    public static String LOGINBTN = "//div[.='Log In']";
    public static String SENDEMAILBTN = "//button[.='Send Email']";
    public static String LOGINPAGELOGO = "//div[@class='page container-xxl']/child::*[local-name()='svg']";
    public static String LOGINHEADER = "//h5[@class='fw-semibold']";
    public static String EMAILLABEL = "//label[@for='loginEmail']";
    public static String ENTEREMAITTORESETPASSWORD = "//label[normalize-space()='Enter Email Address to reset password']";
    public static String PASSWORDLABEL = "//label[normalize-space()='Enter Password']";
    public static String SETYOURPASSWORD = "//div[@class='col-12 position-relative']//span";
    public static String EYEICONLOGIN = "//div[@class='col-12 position-relative']/child::*[local-name()='svg']";
    public static String TEXTSIGNUP = "//div[@class='col-12 text-center mb-4']//small";
    public static String ALREADYHAVEANACTEXT = "//p[@class='m-0']";
    public static String ERROEMSGFORMANDATORY = "//div[@class='invalid-feedback']";
    public static String ORTEXTONLOGIN = "//div[@class='col-12 text-center text-gray-600']";
    public static String DONTHAVEACTEXT = "//p[@class='m-0']";
    public static String LOGINLINK = "//a[@href='/login']";
    public static String BRANDNAME = "//input[@id='name']";
    public static String PREFERREDURL = "//input[@id='subdomain']";
    public static String SAVEBUTTON = "//button[.='Save']";
    public static String PROFILEBRANDTXT = "//h5[@class='fw-semibold']";
    public static String BRANDPHOTO = "(//div//*[local-name()='svg'])[2]";
    public static String BEGENUINELINK = "//span[@class='input-group-text bg-l10-brand-two']";
    public static String CHOOSEBRANDUSERNAME = "//h5[@class='fw-semibold']";
    public static String CHOOSEBRADNTEXT = "//p[contains(text(),'Your branded @username is unique.')]";
    public static String USERNAMELABEL = "//label[@class='form-label']";
    public static String USERNAMEFIELD = "//input[@id='username']";
    public static String CONTINUEBTN = "//button[.='Continue']";
    public static String CONTINUEBTNCREATEBRAND = "//button[@class='btn btn-dark']";
    public static String HEADLINKPHONE = "//h5[@data-sentry-element='CardTitle']";
    public static String TEXTLINKPHONE = "//p[contains(.,'You can use your phone number')]";
    public static String DROPDOWNCOUNTRY = "//select[@class='PhoneInputCountrySelect']";
    public static String PHONENUM = "//input[@autocomplete='tel']";
    public static String SAVEBTN = "//button[@class='btn btn-dark']";
    public static String PROFILEIMG = "//div[@class='user-avatar']";
    public static String LOGOUTBTN = "//span[contains(text(),'Logout')]";
    public static String USERNAMELOGIN = "//span[@class='text-truncate fs-5']";
    public static String MANAGEMENU = "//a[.='Manage']";
    public static String COMMUNITIESMENU = "//span[contains(text(),'Communities')]";
    public static String PROFILE_IMAGE = "(//img[@class='avatar rounded-circle bg-l25-light'])[1]";
    public static String FIRSTCOMUNITIY = "(//div[contains(@class,'flex-grow-1 ms-3 d-flex flex-column align-items-start text-nowrap text-gray-900')])[1]";
    public static String EDITBTN = "//div[@class='position-absolute end-0 bottom-0']//div";
    public static String ENTERPROMPTTXT = "//textarea[@class='form-control mb-3']";
    public static String GENERATEBTN = "//button[contains(.,'Generate')]";
    public static String SAVEBTNCOM = "//button[contains(.,'Save')]";
    public static String MANAGECOMMUNITY = "//a[@href='/manage/communities']";
    public static String GROUPBTN = "//span[contains(text(),'Groups')]";
    public static String FIRSTROUPNAME = "(//div[@class='flex-grow-1 d-flex flex-column align-items-start text-nowrap'])[1]";
    public static String MEMBERBTN = "//button[contains(normalize-space(),'Members (1)')]";
    public static String DOTSMENU = "(//button[@type='button'])[10]";
    public static String REMOVEASMEMBER = "//button[normalize-space()='Remove as Member']";
    public static String SOCIALIMPORT = "//span[.='Social Import']";
    public static String CREATEABRAND = "//button[normalize-space()='Create a brand']";
    public static String BRANDNAMECREATE = "//input[@id='name']";
    public static String OPPSERRORMSG = "//*[contains(text(),'Opps, something went wrong!')";
    public static String RESETPASSWORDYOP = "//a[contains(text(),'Reset Password')]";
    public static String RESETPASSINP = "//input[@id='password']";
    public static String ENTERURL = "//h4[@class='fw-semibold text-gray-900']";
    public static String ENTERURLPARAGRAPH = "//p[@class='mb-0 fw-lighter text-gray-700']";
    public static String BRANDURLS = "//input[@id='url']";
    public static String CONTINUEBUTTON = "//button[@class='btn btn-info px-4']";
    public static String STEP1OF4 = "//p[@class='small text-gray-600 fw-lighter mb-2']";

    //ASSERTPAGE

    public static String ELEMENTYOURWEBSITEURL = "//h4[@class='fw-semibold text-gray-900']";
    public static String UNDERURL = "//p[@class='mb-0 fw-lighter text-gray-700']";
    public static String BYCONTINING = "//div[@class='text-gray-700']";
    public static String CONFIRMBRANDASSERT = "//h4[@class='fw-semibold text-gray-900']";
    public static String ACROSSEBRANDPROFILE = "//p[@class='mb-0 fw-lighter text-gray-700']";
    public static String BRANDLOGO = "//h5[@class='fw-semibold mb-2 text-gray-900']";
    public static String FAVICON = "//small[normalize-space()='Favicon']";
    public static String PROFILE = "//small[normalize-space()='Profile']";
    public static String BANNER = "//small[normalize-space()='Banner']";
    public static String FAVICONIMG = "//div[@class='p-0 border-radius-8 position-relative faviconIconContainer-0-2-6 container-0-2-4']";
    public static String BANNERIMG = "//div[@class='p-0 border-radius-8 position-relative bannerImageContainer-0-2-8 container-0-2-4']";
    public static String PROFILEIMAGE = "//div[@class='p-0 border-radius-8 position-relative profileLogoContainer-0-2-7 container-0-2-4']";
    public static String BRANDSLOGAN = "//h5[contains(.,'Brand Slogan')]";
    public static String BRANDSLOGANLINE = "//p[contains(text(),'Your brand slogan will appear in the center of the')]";

    public static String CUSTOMBUTTON = "//input[@class='form-check-input text-gray-900' and @id='slogan-text']";
    public static String SLOGANIMAGEBUTTON = "//input[@class='form-check-input text-gray-900' and @id='slogan-image']";
    public static String YOURSLOGAN = "//label[@class='form-label' and contains(text(), 'Your Slogan')]";
    public static String WORDDIGIT = "//label[@class='form-label' and contains(text(), '0/24')]";
    public static String SLOGANNAME = "//input[@id='slogan_name']";
    public static String SLOGANIMG = "//img[@class='w-100' and @src='/_next/static/images/slogan-8fd3d6333630ec2a1da256736eee0885.jpg']";
    public static String SELECTFONT = "//label[@class='input-group-text' and contains(text(),'Select Font' )]";
    public static String SELECTFONTDROPDOWN = "//select[@id='select_font_id']";
    public static String FONTWEIGHT = "//label[@class='input-group-text' and contains(text(),'Font Weight' )]";
    public static String FONTWEIGTHDROPDOWN = "//select[@id='select_font_weight']";
    public static String CUSTOMIZEWEBCTAS = "//div[@class='col-6 d-flex align-items-start justify-content-center flex-column']//h5[contains(text(),'Customize Your Web CTAs')]";
    public static String CUTOMIZEWEBCTASPARGRAPH = "//div[@class='col-6 d-flex align-items-start justify-content-center flex-column']//p";
    public static String CUTOMIZEWEBCTASIMG = "//div[@class='col-6 d-flex align-items-center justify-content-end col-xl-5 mt-3 mt-xl-0']//img";
    public static String LOGINDROPDOWN = "//div[@class='selectedValue-0-2-15']";
    public static String MOBILEAPPURL = "//div[@class='row mb-4']//h5";
    public static String MOBILEAPPPARAGRAPH = "//div[@class='row mb-4']//p";
    public static String APPSTOREURL = "//div[@class='d-flex justify-content-between']//label[contains(text(),'App Store URL')]";
    public static String APPSTOREINPUT = "//input[@id='app_store_url']";
    public static String PLAYSTOREURL = "//div[@class='d-flex justify-content-between']//label[normalize-space()='Play Store URL']";
    public static String PLAYSTOREURLINPUT = "//input[@id='play_store_url']";
    public static String POLICYURL = "//div[@class='col-12']//h5[contains(text(),'Policy URLs')]";
    public static String POLICYURLPARAGRAPH = "//div[@class='col-12']//p[contains(text(),'Include URLs for your Terms and Privacy Policy to display on the community platform and redirect users to your site.')]";
    public static String PRIVACYPOLICYTEXT = "//div[@class='d-flex justify-content-between']//label[contains(text(),'Privacy Policy URL')]";
    public static String POLICYINPUT = "//input[@id='privacy_policy']";
    public static String TERMOFUSE = "//div[@class='d-flex justify-content-between']//label[contains(text(),'Terms of Use URL')]";
    public static String TERMSOFUSEURL = "//input[@id='terms_and_condition']";
    public static String IMGSHAREURL = "//div[@class='align-items-center d-flex justify-content-between']//h5[contains(text(),'Image for shared URL')]";
    public static String IMAGEURLINPUT = "//p[@class='small text-gray-600' and contains(text(),'This information will appear when sharing the brand URL.')]";
    public static String PREVIEWMETADATA = "//button[@class='btn btn-outline-info px-4' and @type='submit']";
    public static String PAGETITLE = "//label[@class='form-label' and @for='meta_title']";
    public static String TESTERINNOVATIVE = "//input[@id='meta_title']";
    public static String METADESC = "//label[@class='form-label' and contains(text(),'Meta Description')]";
    public static String METATEXTAREA = "//textarea[@class='form-control']";
    public static String STARTWITH0160 = "//div[@class='d-flex justify-content-between']//label[starts-with(text(),'0/160')]";
    public static String IMAGE = "//h5[@class='fw-semibold text-gray-900 mb-2']";
    public static String BRANDCOLOR = "//h5[starts-with(text(),'Brand Color')]";
    public static String BRANDPARAGRAPH = "//p[@class='small text-gray-600' and contains(text(),'They will be used for interactive elements.')]";
    public static String PRIMARYBOX = "//div[@class='col-12 px-4']//div[@class='row justify-content-between align-items-center border py-3 px-2 mb-3 border-radius-8'][1]";
    public static String PRIMARY = "//div[@class='col-6']//p[contains(.,'Primary')]";
    public static String PRIMARYPARAGRAPH = "//div[@class='col-6']//p[contains(.,'Used for buttons, selected states, and links.')]";
    public static String PRIMARYCOLOR = "(//input[@type='color'])[1]";
    public static String PRIMARYHASH = "//span[@id='primaryCode']";
    public static String PRIMARYCODE = "//input[@aria-describedby='primaryCode']";
    public static String PRIMARYVIEWBOX = "//div[@class='card-body card-body-scrollable']//div//div[1]//div[2]//button[1]//*[name()='svg']";
    public static String SECONDARYBOX = "//div[@class='col-12 px-4']//div[@class='row justify-content-between align-items-center border py-3 px-2 mb-3 border-radius-8'][2]";
    public static String SECONDARY = "//div[@class='col-6']//p[contains(.,'Secondary')]";
    public static String SECONDARYPARAGRAPH = "//div[@class='col-6']//p[contains(.,'Used for text and contrast for backgrounds.')]";
    public static String SECONDARYCOLOR = "(//input[@type='color'])[2]";
    public static String SECONDARYHASH = "//span[@id='secondaryCode']";
    public static String SECONDARYCODE = "//input[@id='secondaryCode']";
    public static String SECONDARYVIEWBOX = "//div[@class='col-12 px-4']//div[2]//div[2]//button[1]//*[name()='svg']";
    public static String TERTIARYBOX = "//div[@class='col-12 px-4']//div[@class='row justify-content-between align-items-center border py-3 px-2 mb-3 border-radius-8'][3]";
    public static String TERTIARY = "//div[@class='col-6']//p[contains(.,'Tertiary')]";
    public static String TERTIARYPARAGRAPH = "//div[@class='col-6']//p[contains(.,'Used for backgrounds and subtle accents.')]";
    public static String TERTIARYCOLOR = "(//input[@type='color'])[3]";
    public static String TERTIARYHASH = "//span[@id='tertiaryCode']";
    public static String TERTIARYCODE = "//input[@id='tertiaryCode']";
    public static String TERTIARYVIEWBOX = "//div[@class='col-12 col-md-9 pb-4']//div[3]//div[2]//button[1]//*[name()='svg']";
    public static String CHANGEBRANDURL = "(//button[@class='btn btn-outline-info px-4'])[2]";
    public static String PREVIEWPAGE = "//div[@class='card-footer-right']//button[@type='button']";
    public static String NEXT = "//div[@class='card-footer-right']//button[@type='submit']";
    public static String STEP2OF4 = "//p[@class='small text-gray-600 fw-lighter mb-2']";
    public static String BRANDCATAGORIES = "(//div[@class='collapse show']//button)[2]";
    public static String ICON = "//div[@class='border-bottom fw-semibold w-100 pb-3 d-flex gap-3']//*[name()='svg']";
    public static String SELECTCATAGORIESOFYOURBRAND = "//h4[@class='fw-semibold text-gray-900']";
    public static String CATAGORIESPARAGRAPH = "//p[@class='mb-0 fw-lighter text-gray-700']";
    public static String CARDBOARD = "//div[@class='card-body card-body-scrollable onboard']";
    public static String ADDCATICON = "//*[name()='path' and contains(@d,'M13 7.5h5v')]";
    public static String NOCATAGORIESFOUND = "//p[@class='mb-0 text-gray-900 fw-semibold mb-1']";
    public static String ALLCTAGORIESDISPLAYED = "//p[@class='small text-gray-600']";
    public static String ADDALLCATAGORY = "//button[normalize-space()='Add Category']";
    public static String CONTINUE = "//div[@class='card-footer-right']";
    public static String NEWCATEGORY = "//h5[@class='offcanvas-title fw-semibold']";
    public static String CLOSEBUTTON = "//button[@aria-label='Close']";
    public static String CATEGORYNAME = "//label[@class='form-label small text-gray-600']";
    public static String CATAGORY_0_24 = "//div[@class='row mb-3']//small[@class='text-gray-500']";
    public static String ENTERCATAGORYNAME = "//input[@placeholder='Enter Category Name']";
    public static String TOPICS = "//legend[@class='h6 form-label mb-0 text-gray-900 fw-semibold']";
    public static String ADD_TOPICS = "//div[@class='align-items-center d-flex col-12']/child::*[2]";
    public static String TOPIC1 = "//h6[contains(@class,'form-label text-gray-900')]";
    public static String TOPIC = "//div[@class='col-12 mb-3']//label[@for='Topic']";
    public static String TOPIC0_24 = "//div[@class='row']//div[@class='col-12 mb-3']//small[@class='text-gray-500']";
    public static String ENTERTOPIC = "//input[@id='msa.0.topics.0.topic_name']";
    public static String KEYWORDS = "(//label[contains(@class,'small mb-2')])[2]";
    public static String KEYWORDS_0_1000 = "(//small[@class='text-gray-500'])[3]";
    public static String ENTERKEYWORDS = "//input[@id='tags']";
    public static String PRESSENTERAFTERTEXT = "//small[@class='text-gray-600']";
    public static String ADDBUTTON = "//button[@type='submit']";
    public static String CHECKBOX = "(//input[@type='checkbox'])[last()]";
    public static String TITLEOFINPUT = "(//div[@role='button'])[last()]//*[@class='text-gray-900 mb-0 category-name']";
    public static String LISTOFTOPIC = "//span[@class='fw-medium mb-3 text-gray-900 topic-name w-100']";
    public static String ADDTOPIC = "(//button[contains(@class,'btn border-transparent')])[2]";
    public static String UPBUTTON = "//div[@class='accordion-header rounded-1 d-flex flex-column cursor-pointer active']//div[@class='up-down-arrow']";
    public static String ALERTTEXT = "//div[@role='alert']";
    public static String ADDCATAGORYBUTTON = "//button[@class='btn btn-light-info']";

    //Add Brand
    public static String ADDBRANDTOEARN = "//button[@class='btn btn-light-undefined border-radius-12 text-gray-800']";
    public static String ADDCONSUMER = "//h5[@id='upcomingEdit']";
    public static String BRANDHANDLE = "//div[@data-sentry-element='TagWrapper']//label[@for='website url']";
    public static String SEARCHICON = "//span[@id='addon1']";
    public static String SEARCHBYBRANDHANDLE = "//input[@id='genuin_id']";
    public static String NOTFOUND = "//p[@class='mb-0 small ps-3']";
    public static String NEWBRAND = "//button[@class='btn btn-light-undefined align-items-center border-0 d-flex gap-2']";
    public static String BRANDNAMEINPUT = "//input[@id='brand_name']";
    public static String CONTACTEMAILS = "//div[@class='align-items-center d-flex justify-content-between']//label[@for='website url']";
    public static String PREVIEWTEMPLATE = "//label[@class='form-label form-label small text-primary cursor-pointer']";
    public static String EMAILPLACEHOLDER = "//input[@placeholder='name@work-email.com']";
    public static String CONTACTEMAILREQUIRE = "//p[@class='text-danger small mt-1']";
    public static String INVITE = "//button[@class='btn btn-light-undefined w-100 text-start border border-radius-8 text-gray-700 bg-primary-subtle']";
    public static String WEBSITEURL = "//label[@for='brand url']";
    public static String ENTERBRANDWEBSITE = "//input[@id='brand_URL']";
    public static String EARNINGCPMFLOORPRICE = "//label[@for='cpm']";
    public static String Cpm = "//span[@class='input-group-text text-gray-700 fw-medium']";
    public static String ENTERCPM = "//input[@id='cpm']";
    public static String COMMUNITYFEEDACCESS = "//label[@class='form-label' and text()='Community Feed Access Period']";
    public static String Startdate = "//input[@id='startDate']";
    public static String ENDDATE = "//input[@id='endDate']";
    public static String SOCIALMEDIAHANDLE = "//form//label[@for='website url']";
    public static String SELECTSOCIALMEDIA = "//button[@aria-label='Select social media']";
    public static String YOUTUBEHANDLE = "//input[contains(@id,'handles')]";
    public static String ADDSOCIALHANDLE = "//button[@class='btn border-transparent text-primary px-0 py-2 text-primary']";
    public static String CLICKADDSOCIALHANDLE = "(//input[@placeholder='YouTube handle'])[2]";
    public static String ADD = "//button[@class='btn btn-info']";
    public static String Cancel = "//button[@class='btn btn-outline-info border-transparent ms-3']";

    //Engage Page
    public static String DATALOGSFORENAGE = "//a[@href='/engage/data-logs']//span[@class='navigation-link-info']";
    public static String HOMEPAGE = "//button[@class='btn btn-only-icon bg-gray-100 border-radius-8 text-gray-600']";
    public static String SOCIALIMPORTONDATALOGS = "//button[@class='btn btn-info active fw-medium']";
    public static String UPLOADS = "//button[contains(.,'Uploads')]";
    public static String CLIPIT = "//button[contains(.,'Clip it')]";
    public static String IMPORTS = "//h5[@class='fw-semibold']";
    public static String DURATIONTIME = "//button[@class='btn btn-light-undefined text-black bg-gray-100 fw-medium']";
    public static String STATUS = "//span[contains(.,'Status')]";
    public static String SELECTSTATUS = "//div[@class='selectedValue-0-2-15']";
    public static String ALLSTATUS = "//li[contains(.,'All')]";
    public static String PROCESSING = "//li[contains(.,'Processing')]";
    public static String COMPLETED = "//li[contains(.,'Completed')]";
    public static String FAILED = "//li[contains(.,'Failed')]";
    public static String FILTER = "//button[@class='btn btn-light-info']";
    public static String PAGINATIONFOOTER = "//div[@class='card-footer-left']";
    public static String PAGE_COUNT = "//select[@aria-label='Per']";
    public static String SOURCE = "//span[contains(.,'Source')]";
    public static String SELECTSOURCE = "//div[@style='width: 180px; border-radius: 0px 12px 12px 0px;']";
    public static String UPLOADFROMCOMPUTER = "//li[normalize-space()='Your Computer']";
    public static String UPLOADFROMGOOGLEDRIVE = "//li[normalize-space()='Google Drive']";
    public static String UPLOADFROMDROPBOX = "//li[normalize-space()='Dropbox']";
    public static String UPLOADFROMS3BUCKET = "//li[normalize-space()='S3 Bucket']";
    public static String DATE = "//th[@aria-label='Date-col']";
    public static String IMPORTEDBY = "//th[@aria-label='Imported by-col']";
    public static String IMPORTSTATUS = "//th[@aria-label='Import status-col']";
    public static String TOTALBRANDS = "//th[@aria-label='Total brands-col']";
    public static String TOTALSUBMITTED = "//th[@aria-label='Total submitted-col']";
    public static String TOTALIMPORTED = "//th[@aria-label='Total imported-col']";
    public static String TOTALAPPROVED = "//th[@aria-label='Total approved-col']";
    public static String NOTE = "//th[@aria-label='Note-col']";
    public static String NAME = "//th[contains(.,'Name')]";
    public static String IMPORTBY = "//th[@class='p-3 text-gray-800']";
    public static String SOURCELABEL = "//th[contains(.,'Source')]";
    public static String DATELABEL = "//th[contains(.,'Date')]";
    public static String IMPORTSTATUSLABEL = "//th[contains(.,'Import status')]";
    public static String POSTED = "//th[@style='width: 12%; min-width: 8px;']";
    public static String SOURCEVIDEO = "//th[@style='width: 20%; min-width: 8px;']";
    public static String SOURCEFORCLIPIT = "//th[.='Source']";
    public static String IMPORTAT = "//th[.='Imported at']";
    public static String IMPORTSTATUSFORCLIP = "//th[.='Import status']";
    public static String GENERATEDAT = "//th[.='Generated at']";
    public static String TOTALCREATED = "//th[.='Total created']";
    public static String TOTALPOSTED = "//th[.='Total posted']";

    public static String ACTIVITY = "//ul[@id='header-top-menu']//a[@class='navigation-link navigation-link-pill active']";
    public static String IMPORTVIDEOS = "//a[@href='/engage/import-videos']";
    public static String VIDEOIMAGE = "//img[@alt='text'][last()]";
    public static String REJECT = "//button[@class='btn btn-outline-danger border-transparent']";
    public static String REJECTDESC = "//textarea[@id='reason']";

    public static String SUBMIT = "//button[@type='submit']";
    public static String DATALOGS = "//a[@href='/engage/data-logs']";
    public static String PROCESSINGFORENAGE = "(//button[@type='button'])[6]";
    public static String AWAITAPPROVAL = "(//button[@type='button'])[7]";
    public static String APPROVED = "(//button[@type='button'])[8]";
    public static String REJECTED = "(//button[@type='button'])[9]";
    public static String ALLBUTTON = "//button[@class='btn btn-info']";
    public static String PENDINGBUTTON = "(//button[@class='btn btn-light-info'])[1]";
    public static String APPROVEDBUTTON = "(//button[@class='btn btn-light-info'])[2]";
    public static String REJECTEDBUTTON = "(//button[@class='btn btn-light-info'])[3]";
    public static String FILTERBY = "//div[@class='input-group']//label[1]";
    public static String DROPDOWN = "//div[@class='input-group']//select[1]";
    public static String COMMUNITIES = "//div[@role='button']";
    public static String SHOWINGCOMMUNITIES = "//div[@class='d-flex align-items-center gap-3']";
    public static String LEFTARROW = "//div[@class='d-flex align-items-center gap-3']//button[1]";
    public static String RIGHTARROW = "//div[@class='d-flex align-items-center gap-3']//button[2]";
    public static String CIRCLESYMBOL = "//img[@class='avatar rounded-circle bg-l25-primary overflow-hidden']";
    public static String HEADING = "//h4[contains(@class,'fw-semibold text-black')]";
    public static String ALLCOMMUNITIESBOX = "(//div[contains(@class,'p-4 border')])[1]";
    public static String EDITBUTTON = "(//*[name()='svg'][@class='flex-shrink-0'])[1]";
    public static String EDITCOMMUNITY = "//h5[@id='edit-community-canvas']";
    public static String COMMUNITYDETAILS = "//p[@class='fw-semibold text-gray-900']";
    public static String BACKBUTTON = "//button[@class='btn-close text-reset']";
    public static String PHOTOICON = "(//div[@class='offcanvas-body']//div)[4]";
    public static String COMMUNITYNAME = "(//label[@class='form-label'])[1]";
    public static String COMMUNITYWORDS = "(//label[@class='form-label'])[2]";
    public static String COMMUNITYINPUT = "//input[@id='name']";
    public static String COMMUNITYHANDLE = "(//label[@class='form-label'])[3]";
    public static String COMMUNITYHANDLEWORDS = "(//label[@class='form-label'])[4]";
    public static String HANDLEINPUT = "//input[@id='handle']";
    public static String DESCRIPTION = "(//label[@class='form-label'])[5]";
    public static String DESCRIPTIONWORDS = "(//label[@class='form-label'])[6]";
    public static String DESCRIPTIONINPUT = "//textarea[@id='description']";
    public static String SAVEBUTTONFORCOMMUNITY = "(//button[@data-sentry-source-file='EditCommunityOffCanvas.tsx'])[1]";
    public static String CANCELBUTTON = "(//button[@data-sentry-source-file='EditCommunityOffCanvas.tsx'])[2]";
    public static String NAMEALERT = "//input[@class='form-control is-invalid']/following-sibling::div[1]";
    public static String HANDLEALERT = "(//input[contains(@class,'form-control is-invalid')]/following-sibling::div)[2]";
    public static String DESCRIPTIONALERT = "//textarea[@class='form-control is-invalid']/following-sibling::div[1]";
    public static String ICONLOGOSAVE = "//button[@class='btn text-info']/following-sibling::button[1]";
    public static String EDITGROUPBUTTON = "(//*[name()='svg'][@class='flex-shrink-0'])[2]";
    public static String EDITGROUPTEXT = "//h5[@id='edit-loop-canvas']";
    public static String EDITGROUPBACKBUTTON = "//button[@class='btn-close text-reset']";
    public static String GROUPDETAILS = "//p[@class='fw-medium text-gray-900']";
    public static String EDITGROUPNAME = "//span//label[@for='name']";
    public static String EDITGROUPNAMECOUNT = "(//label[@class='form-label'])[2]";
    public static String GROUPNAMEINPUT = "//input[@id='name']";
    public static String EDITDESCRIPTION = "(//label[@class='form-label'])[3]";
    public static String EDITDESCRIPTIONCOUNT = "(//label[@for='description'])[2]";
    public static String EDITDESCRIPTIONINPUT = "//textarea[@id='description']";
    public static String EDITSAVEBUTTON = "(//button[@class='btn btn-info'])[2]";
    public static String EDITCANCELBUTTON = "(//button[@data-sentry-element='Button']/following-sibling::button)[3]";
    public static String EDITGROUPNAMEALERT = "(//div[@class='invalid-feedback'])[1]";
    public static String EDITGROUPDESCRIPTIONALERT = "(//div[@class='invalid-feedback'])[2]";
    public static String EDITGROUPHEADING = "(//div[@class='p-4 border rounded-4 position-relative']//.)[4]";
    public static String VIDEOBOXES = "//img[@alt='text']";
    public static String AWAITAPPROVALCOUNT = "(//button[@type='button'])[7]//*[@class='fw-semibold']";
    public static String APPROVEDCOUNT = "(//button[@type='button'])[8]//*[@class='fw-semibold']";
    public static String REJECTEDCOUNT = "(//button[@type='button'])[9]//*[@class='fw-semibold']";
    public static String SOCIALIMPORTFORIMPORTVIDEOS = "(//div[@class='flex-shrink-1'])[1]";
    public static String UPLOADSFORIMPORTVIDEOS = "(//div[@class='flex-shrink-1'])[2]";
    public static String CLIPITFORIMPORTVIDEOS = "(//div[@class='flex-shrink-1'])[3]";
    public static String FROMURL = "(//div[@class='flex-shrink-1'])[4]";
    public static String BLOGTOVIDEO = "(//div[@class='flex-shrink-1'])[5]";
    public static String GENERATEDVIDEOSTITLE = "//div[@class='card-title-wrapper']//h5";
    public static String SEARCHINPUT = "//input[@id='searchInput']";
    public static String GENRATEDVIDEOS = "//ul[@class='col-12']";
    public static final String IMPORTINFORSOCIALIMPORT = "//h5[@class='card-title fw-medium h6']";
    public static String ALLCOMMUNITIESFORSOCIALIMPORT = "(//span[@class=\"p-2 ps-3 text-truncate\"])[1]";
    public static String ALLGROUPSFORSOCIALIMPORT = "(//span[@class=\"p-2 ps-3 text-truncate\"])[2]";
    public static String VIDEOWILLTEXTFORSOCIALIMPORT = "//p[@class='text-gray-600 mt-3 mb-0 small']";
    public static String TODATALOGSBUTTON = "//button[@class='btn btn-light-info btn-only-icon']";
    public static String ALLFORSOCIALIMPORT = "//button[@class='btn btn-light-info w-100 p-3 text-start px-2']";
    public static String MYBRANDFORSOCIALIMPORT = "//button[@class='btn w-100 p-3 text-start px-2'][contains(text(),'My Brand')]";
    public static String CONSUMERBRANDFORSOCIALIMPORT = "//button[@class='btn w-100 p-3 text-start px-2'][contains(text(),'Consumer brands')]";
    public static String SELECTALLCHECKBOX = "//input[@id='checkbox-select-all']";
    public static String SELECTALL = "//label[@class='custom-checkbox-label']";
    public static String SEARCHFORBRAND = "//input[@class='form-control']";
    public static String IMPORTBUTTONFORSOCIALIMPORT = "//div[@class='card-footer-right']";
    public static String IMPORTINFORUPLOADS = "//span[@class='fw-medium']";
    public static String ALLCOMMUNITIESFORUPLOADS = "(//span[@class=\"p-2 ps-3 text-truncate\"])[1]";
    public static String ALLGROUPSFORUPLOADS = "(//span[@class=\"p-2 ps-3 text-truncate\"])[2]";
    public static String VIDEOWILLTEXTFORUPLOADS = "//p[@class='text-gray-600 mt-3 mb-0 small']";
    public static String FILEUPLOADAREAFORUPLOADS = "//label[@for='file']";
    public static String SETTINGSFORUPLOADS = "(//div[@class='col-12']//p)[1]";
    public static String SETTINGSOPTIONSBOXFORUPLOADS = "(//div[@class='d-flex flex-shrink-0 flex-wrap gap-3'])[1]";
    public static String ADVANCEDFORUPLOADS = "(//div[@class='col-12']//p)[2]";
    public static String ADVANCEDOPTIONSBOXFORUPLOADS = "(//div[@class='d-flex flex-shrink-0 flex-wrap gap-3'])[2]";
    public static String IMPORTBUTTONFORUPLOADS = "//div[@class='card-footer-right']";
    public static String IMPORTINFORCLIPIT = "//span[@class='fw-medium']";
    public static String ALLCOMMUNITIESFORCLIPIT = "(//span[@class=\"p-2 ps-3 text-truncate\"])[1]";
    public static String ALLGROUPSFORCLIPIT = "(//span[@class=\"p-2 ps-3 text-truncate\"])[2]";
    public static String VIDEOWILLAUTOMATICALLYFORCLIPIT = "//p[@class='text-gray-600 mt-3 mb-0 small']";
    public static String URLICONFORCLIPIT = "//span[@class='input-group-text']";
    public static String VIDEOURLINPUT = "//input[@id='video-url']";
    public static String DROPLINK = "//p[@class='text-gray-600 small mt-3']";
    public static String ADDYOUROWNMEDIA = "//p[@class='text-gray-600 small mt-3']/following-sibling::div[1]";
    public static String FILEUPLOADAREAFORCLIPIT = "//label[@for='file']";
    public static String CLIPPINGCONTENT = "//p[@class='small text-gray-600']";
    public static String SETTINGSFORCLIPIT = "(//div[@class='col-12']//p)[1]";
    public static String SETTINGSOPTIONSBOXFORCLIPIT = "(//div[@class='d-flex flex-shrink-0 flex-wrap gap-3'])[1]";
    public static String ADVANCEDFORCLIPIT = "(//div[@class='col-12']//p)[2]";
    public static String ADVANCEDOPTIONSBOXFORCLIPIT = "(//div[@class='d-flex flex-shrink-0 flex-wrap gap-3'])[2]";
    public static String GETCLIPSFORCLIPIT = "//div[@class='card-footer-right']";
    public static String CLIPSBEINGPROCESING = "//div[@class='row w-100']//div[@class='col']";
    public static String VIDEOUPLOADEDFORCLIPIT = "//span[normalize-space()='100%']";
    public static String VIDEOUPLOADLOCATIONCLIPIT = "//label[@for='file']/input[@type='file']";
    //Embed Page
    public static String ONSITE = "//ul[@id='header-top-menu']//a[@class='navigation-link navigation-link-pill active']";
    public static String OFFSITE = "//a[@href='/grow/off-site']";
    public static String QUESTS = "//a[@href='/grow/quests']";
    public static String EMBEDSTEXT = "//h4[@class='card-title h4']";
    public static String DOWNLOADBUTTON = "//button[@class='btn btn-light-info btn-only-icon']";
    public static String NEWEMBED = "//button[@class='btn btn-light-info']";
    public static String SEARCHICONFOREMBED = "//span[@class='input-group-text px-2']";
    public static String SEARCHINPUTFORCOMMENT = "//input[@id='search-input']";
    public static String GLOBALANALYTICS = "//div[@class='d-flex rounded-1 border gap-2 mb-3 p-3 border-primary']";
    public static String CARDBODY = "//div[@class='card-body card-body-scrollable']";
    public static String EDITEMBED = "//div[@class='card card-stretch-full']//div[1]//div[1]//div[2]//button[1]//*[name()='svg']";
    public static String BLOGEMBED = "//body/div[@id='__next']/div[@class='app']/div[@class='wrapper']/main[@class='content']/div[@class='page-wrapper container-fluid']/div[@class='page embed container-fluid']/div[@class='row h-100']/div[@class='col embed-container-left']/div[@class='card card-stretch-full']/div[@class='card-body card-body-scrollable pt-0']/div/div[2]";
    public static String HOMESEARCHEMBED = "(//div[@role='button'])[2]";
    public static String HOMESEARCH = "(//div[@role='button'])[4]";
    public static String POSTSALESEMBED = "(//div[@role='button'])[5]";
    public static String PDPEMBED = "(//div[@role='button'])[6]";
    public static String HOMEBLOGEMBED = "(//div[@role='button'])[7]";
    public static String HOMEPOSTSALESEMBED = "(//div[@role='button'])[8]";
    public static String EMBEDNAME = "//span[@class='input-group-text text-gray-600 fw-medium']";
    public static String NAMEOFEMBED = "//input[@aria-label='Embed 1']";
    public static String EMBEDTYPE = "//label[normalize-space()='Embed Type']";
    public static String SELECTEMBEDTYPE = "//select[@id='embed']";
    public static String BRANDFEED = "//option[.='Brand Feed']";
    public static String COMMUNITYFEED = "//option[.='Community Feed']";
    public static String GROUPFEED = "//option[.='Group Feed']";
    public static String EMBEDSTYLE = "//label[.='Embed Style']";
    public static String SELECTEMBEDSTYLE = "//select[@id='embed-style']";
    public static String STANDAEDWALL = "//option[.='Standard Wall']";
    public static String FEED = "//option[.='Feed']";
    public static String CAROUSEL = "//option[.='Carousel']";
    public static String MONITORBUTTON = "//button[@class='btn btn-info btn-only-icon active border-radius-4']";
    public static String MOBILEBUTTON = "//button[@class='btn btn-light-info btn-only-icon border-radius-4 ms-2']";
    public static String VIEWSETTINGS = "//h5[@class='fw-semibold text-gray-800 mb-0']";
    public static String EMBEDSIZE = "//h5[.='Embed Size']";
    public static String SHOWHEADER = "//h5[.='Show Header']";
    public static String DISPLAYTOPNAVBAR = "//p[.='Display the top nav bar']";
    public static String SHOWNEVIGATIONBUTTON = "//input[@id='showNavigation']";
    public static String SHOWSIDEPANEL = "//h5[.='Show Side Panel']";
    public static String SHOWSIDEPANELBUTTON = "//input[@id='showSidePanel']";
    public static String SHOWJOINCOMMUNITY = "//h5[.='Show Join Community Button']";
    public static String SHOWJOINCOMMUNITYBUTTON = "//input[@id='showJoinCommunityButton']";
    public static String SHOWCOMMUNITYSHAREBUTTON = "//input[@id='showCommunityShareButton']";
    public static String ENGAGEMENTDETAILS = "//h5[.='Engagement Details']";
    public static String ENABLEENGAGEMENTTOOL = "//input[@id='enableEngagementTools']";
    public static String ENABLEREDIRECTION = "//h5[.='Enable Redirection']";
    public static String ENABLEREDIRECTIONBUTTON = "//input[@id='enableRedirection']";
    public static String LINKS = "//h5[.='Links']";
    public static String SHOWLINKSBUTTON = "//input[@id='showLinks']";
    public static String MEDIAPLAY = "//h5[.='Media Play']";
    public static String LOOPVIDEOBUTTON = "//input[@id='loopVideo']";
    public static String GENERATECODE = "//button[@class='btn btn-info']";
    public static String CANCELFOREMBED = "//button[@class='btn btn-outline-info border-transparent']";
    public static String CONFIRMFOREMBED = "//button[.='Confirm']";
    public static String MONITERBUTTONFOREMBED = "//button[@class='btn btn-light-info btn-only-icon border-radius-4']";
    public static String EMBEDVIEW = "//button[.='Embed View']";
    public static String POPUPVIEW = "//button[.='Pop Up View']";
    public static String TITLE = "//h5[.='Title']";
    public static String HEADLINE = "//label[.='Headline']";
    public static String ENTERHEADLINE = "//input[@id='headline']";
    public static String HEADLINETEXTCOLOR = "//h5[.='Headline Text Color']";
    public static String COLORFORHEADLINE = "(//input[@class='form-control form-control-color border-radius-8 p-0 border-0 shadow-none'])[1]";
    //  public static String COLORFORHEADLINE="(//input[@class='form-control form-control-color border-radius-8 p-0 border-0 shadow-none'])[1]";
    public static String SUBHEADLINE = "//label[.='Sub Headline']";
    public static String ENTERSUBHEADLINE = "//input[@id='subHeadline']";
    public static String SUBHEADLINETEXTCOLOR = "//h5[.='Sub Headline Text Color']";
    public static String COLORFORSUBHEADLINE = "(//input[@class='form-control form-control-color border-radius-8 p-0 border-0 shadow-none'])[2]";
    public static String BUTTON = "//h5[.='Button']";
    public static String CHECKHIDEBUTTON = "//input[@id='checkedHideButton']";
    public static String VIEWSETTINGSFORFEED = "//h5[.='View Settings']";
    public static String ADJUSTDIMENSION = "//p[.='Adjust the dimensions of the embed frame']";
    public static String ENABLEFLOATINGVIEW = "//h5[.='Enable Floating View']";
    public static String ENABLEFLOATINGVIEWBUTTON = "//input[@id='enableFloatingView']";
    public static String SHOWUSERNAME = "//h5[.='Show Username']";
    public static String SHOWUSERNAMEBUTTON = "//input[@id='showUsername']";
    public static String SHOWVIEWCOUNT = "//h5[.='Show View Count']";
    public static String SHOWVIEWCOUNTBUTTON = "//input[@id='showViewCount']";
    public static String SHOWSOCIALINTEGRATIONDATA = "//h5[.='Show Social Interaction Data']";
    public static String SHOWSOCIALINTEGRATIONDATABUTTON = "//input[@id='showSocialInteractionData']";
    public static String AUTOPLAYVIDEO = "//h5[.='Autoplay Video']";
    public static String AUTOPLAYVIDEOBUTTON = "//input[@id='autoplayVideo']";
    public static String LOOPVIDEO = "//h5[.='Loop Video']";
    public static String SAVEANDUPDATE = "//button[.='Save and Update']";
    public static String ENABLEPOPUPVIEW = "//h5[.='Enable Pop Up view']";
    public static String ENABLEPOPUPVIEWBUTTON = "//input[@id='enablePopUpView']";
    public static String BACKTOHOME = "//*[name()='path' and contains(@d,'M8 4l-6 6v')]";
    public static String importButton = "//span[contains(text(),'Import Videos')]";
    public static String EDIT = "(//button[@aria-expanded='false'])[1]";
    public static String EDITEMBEDNAME = "//button[normalize-space()='Edit Embed']";
    public static String MARKASACTIVE = "//input[@class='form-check-input']";
    public static String VIEWEMBEDCODE = "//button[.='View Embed Code']";
    public static String UPCOMINGEDIT = "//h5[@id='upcomingEdit']";
    public static String WEBBUTTON = "//button[.='Web']";
    public static String IOSBUTTON = "//button[.='iOS']";
    public static String ANDROIDBUTTON = "//button[.='Android']";
    public static String REACTNATIVEBUTON = "//button[.='React Native']";
    public static String FLUTERBUTTON = "//button[.='Flutter']";
    public static String CANCEL = "//button[@class='btn btn-info ms-3']";
    public static String COMMUNITY="//span[@class='p-2 border-end text-gray-600 px-3 fw-medium']";
    public static String SELECTCOMMUNITY="//div[@role='button']";
    public static String SELECTONECOMMUNITY="//div[@class='custom-dropdown']//div[1]//div[1]//input[1]";
    public static String SELECTTWOCOMMUNITY="//div[@class='custom-dropdown']//div[3]//div[1]//input[1]";
    public static String DROPDOWNFORSELECTCOMMUNITY="//div[@class='d-flex align-items-center gap-2 pe-2']";
    public static String SELECTGROUP="(//div[@class='custom-dropdown-item gap-3']//input[@type='checkbox'])[1]";
    public static String SEARCHICONFORCOMMUNITY="//div[@class='custom-dropdown-wrap bottom z-3']//div[@class='custom-dropdown-search']//*[name()='svg']";
    public static String SEARCHCOMMUNITY="//input[@placeholder='Search Community']";
    public static String SEARCHICONFORGROUP="div[class='submenuContainer-0-2-50'] div[class='custom-dropdown-search'] svg";
    public static String SEARCHGROUP="//input[@placeholder='Search Group']";
    public static String EDITEMBEDFORDUPLICATE="//div[@class='card-body card-body-scrollable pt-0']//div[2]//div[1]//div[2]//button[1]";
    public static String DUPLICATEEMBED="//button[normalize-space()='Duplicate Embed']";
    public static String CARDHEADER="//div[@class='card-header']";
    public static String ADDCREATIVES="//h5[.='Ad Creatives']";
    public static String FILTERBUTTON="//button[@class='btn btn-light-info border-radius-9 padding-left-8 padding-right-8']";
    public static String NEWAD="//button[@class='btn btn-light-info border-radius-12']";
    public static String ALLFILTER="//span[normalize-space()='All']";
    public static String ACTIVEADS="//span[normalize-space()='Active Ads']";
    public static String DEACTIVEADS="//span[normalize-space()='Deactivated Ads']";
    public static String DISPLAYADS ="//div[@class='card-body card-body-scrollable pt-0']";
    public static String ADDSBUTTON="//div[@class='card border-radius-10 shadow-none ad-card isSelected']//button[@type='button']//button[@type='button']";
    public static String EDITAD="//small[normalize-space()='Edit Ad']";
    public static String DEACTIVATEDADD="//input[@class='form-check-input']";
    public static String SELCTPOSTFORAD="//h5[@class='card-title fw-medium h5 fw-semibold']";
    public static String SEARCHICONFORPOST="//span[@class='input-group-text py-0']";
    public static String FILTERFORPOST="//button[@class='btn btn-light-info border-radius-9 padding-left-8 padding-right-8 px-3']";
    public static String SELECTPOST="(//input[@type='checkbox'])[1]";
    public static String CANCELFORPOST="//button[@class='btn btn-outline-primary border-transparent']";
    public static String NEXTBUTTONFORPOST="//button[@class='btn btn-info px-3']";
    public static String ADDITINALDETAILS="//h5[@class='card-title fw-semibold']";
   // pulic static String POSTS
    public static String ADCOPY="//th[@aria-label='Ad Copy-col']";
    public static String CALLTOACTION="//th[@aria-label='Call-to-Action-col']";
    public static String FETCHMETADATA="//th[@aria-label='Fetch Metadata-col']";
    public static String HASHTAGS="//th[.='Hashtags']";
    public static String PIXELURL="//th[.='Pixel URL']";
    public static String EDITPOST="//span[@class='fw-medium']";
    public static String FITTIHEIGHT="//input[@id='fit-to-height']";
    public static String FITTOWIDTH="//input[@id='fit-to-width']";
    public static String FILL="//input[@id='fill']";
    public static String IMAGEOFPOST="//img[@alt='Profile']";
    public static String ENTERADCOPY="//textarea[@id='posts.0.cta.ad_copy']";
    public static String CALLACTIONTEXT="//input[@id='posts.0.cta.text']";
    public static String CALLACTIONLINK="//input[@id='posts.0.cta.link']";
    public static String CLICKONMETADATA="//input[@id='posts.0.cta.show_url_meta']";
    public static String ADDHASHTAGS="//textarea[@id='posts.0.cta.hashtags']";
    public static String ENTERPIXELURL="//textarea[@id='posts.0.cta.pixel_url']";
    public static String CANCELFORDETAILS="//button[@class='btn btn-outline-info border-transparent px-3']";
    public static String SAVEFORDETAILS="//button[@style='width: 250px;']";
    public static String ADDNAME="//span[@class='input-group-text text-gray-600 fw-medium']";
    public static String ENTERADNAME="//input[@id='adName']";
    public static String EDITPOSTS="//button[.='Edit Posts']";
    public static String TRACKINGDETAILS="//h5[.='Tracking Details']";
    public static String GOOGLETAGMANAGERID="//label[@class='form-label']";
    public static String ENTERMANAGERID="//input[@id='gtmi']";
    public static String EDITADCREATIVE="//h5[.='Edit Ad Creative']";
    public static String SIZE="//span[.='Size']";
    public static String NUMBEROFSIZE="//div[@class='row m-0 mb-4']//div[@class='selectedValue-0-2-15']";
    public static String BUTTONDELAY="//span[.='Button Delay']";
    public static String DEALY="//div[@class='row m-0']//div[@class='selectedValue-0-2-15']";
    public static String VIEWDETAILS="//h5[.='View Details']";
    public static String REDIRECTTOPROFILE="//input[@id='redirectToProfile']";
    public static String VIEWCODE="//button[normalize-space()='View Code']";
    public static String WEBAD="//div[@class='offcanvas-header']";
    //public static String CANCELBUTTON
    public static String SEARCHINPUTFORREORDER = "//input[@id='searchInput']";
    public static String POSTS = "//th[@aria-label='posts-col']";


}

